spring.application.name=rest-api

spring.kafka.bootstrap-servers=${KAFKA_BROKERS:localhost:9092}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.group-id=rest-api
spring.kafka.consumer.auto-offset-reset=latest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=*
spring.kafka.consumer.properties.spring.json.use.type.headers=false
spring.kafka.consumer.properties.spring.json.value.default.type=java.util.Map

server.port=8085
admin.secret-key=dev-exchange-admin-token
admin.service.url=${ADMIN_SERVICE_URL:http://localhost:8083}
market.events.url=${MARKET_EVENTS_URL:http://market-events:8082}
kafka.topics.admin-commands=admin.commands
kafka.topics.stock-prices=stock.prices
kafka.topics.orders-requests=orders.requests
kafka.topics.orders-updates=orders.updates
kafka.topics.market-events=market.events