package lynx.team2.rest_api.models;

import lynx.team2.rest_api.LUtils;

public class Order {
    private String order_id;            // Unique identifier generated by the exchange
    private String platform_id;         // The broker platform that submitted this order
    private String platform_user_id;    // The user on that platform who placed the order
    private String instrument_type;     // "STOCK" or "OPTION"
    private String instrument_id;       // Ticker (for stocks) or option_id (for options)
    private String order_type;          // "MARKET" or "LIMIT"
    private String side;                // "BUY" or "SELL"
    private int quantity;               // Number of shares or contracts
    private double limit_price;          // Required for LIMIT orders. Null for MARKET orders
    private String status;              // See Order Lifecycle (Section 3.5)
    private int filled_quantity;        // How many units have been filled so far
    private double average_fill_price;   // Weighted average price of executed fills
    private double exchange_fee;         // Total exchange fee charged on this order (populated on fill)
    private long created_at;            // Simulated market timestamp of order creation
    private long updated_at;            // Simulated market timestamp of last status change
    private long expires_at;            // For LIMIT orders: simulated market time after which order is cancelled

    public Order(String order_id, String platform_id, String platform_user_id, String instrument_type, String instrument_id, String order_type, String side, int quantity, double limit_price, String status, int filled_quantity, double average_fill_price, double exchange_fee, long created_at, long updated_at, long expires_at) {
        this.order_id = order_id;
        this.platform_id = platform_id;
        this.platform_user_id = platform_user_id;
        this.instrument_type = instrument_type;
        this.instrument_id = instrument_id;
        this.order_type = order_type;
        this.side = side;
        this.quantity = quantity;
        this.limit_price = limit_price;
        this.status = status;
        this.filled_quantity = filled_quantity;
        this.average_fill_price = average_fill_price;
        this.exchange_fee = exchange_fee;
        this.created_at = created_at;
        this.updated_at = updated_at;
        this.expires_at = expires_at;
    }

    public String getOrder_id() { return order_id; }
    public String getPlatform_id() { return platform_id; }
    public String getPlatform_user_id() { return platform_user_id; }
    public String getInstrument_type() { return instrument_type; }
    public String getInstrument_id() { return instrument_id; }
    public String getOrder_type() { return order_type; }
    public String getSide() { return side; }
    public int getQuantity() { return quantity; }
    public double getLimit_price() { return limit_price; }
    public String getStatus() { return status; }
    public int getFilled_quantity() { return filled_quantity; }
    public double getAverage_fill_price() { return average_fill_price; }
    public double getExchange_fee() { return exchange_fee; }
    public String getCreated_at() { return LUtils.longToIsoDate(created_at); }
    public String getUpdated_at() { return LUtils.longToIsoDate(updated_at); }
    public String getExpires_at() { return LUtils.longToIsoDate(expires_at); }
}
