package lynx.team2.rest_api.models;

import lynx.team2.rest_api.LUtils;

public class Order {
    private String order_id;            // Unique identifier generated by the exchange
    private String platform_id;         // The broker platform that submitted this order
    private String platform_user_id;    // The user on that platform who placed the order
    private String instrument_type;     // "STOCK" or "OPTION"
    private String instrument_id;       // Ticker (for stocks) or option_id (for options)
    private String order_type;          // "MARKET" or "LIMIT"
    private String side;                // "BUY" or "SELL"
    private Integer quantity;               // Number of shares or contracts
    private Double limit_price;          // Required for LIMIT orders. Null for MARKET orders
    private String status;              // See Order Lifecycle (Section 3.5)
    private Integer filled_quantity;        // How many units have been filled so far
    private Double average_fill_price;   // Weighted average price of executed fills
    private Double exchange_fee;         // Total exchange fee charged on this order (populated on fill)
    private Long created_at;            // Simulated market timestamp of order creation
    private Long updated_at;            // Simulated market timestamp of last status change
    private Long expires_at;            // For LIMIT orders: simulated market time after which order is cancelled

    public Order(String order_id,
                 String platform_id,
                 String platform_user_id,
                 String instrument_type,
                 String instrument_id,
                 String order_type,
                 String side,
                 Integer quantity,
                 Double limit_price,
                 String status,
                 Integer filled_quantity,
                 Double average_fill_price,
                 Double exchange_fee,
                 Long created_at,
                 Long updated_at,
                 Long expires_at
    ) {
        this.order_id = order_id;
        this.platform_id = platform_id;
        this.platform_user_id = platform_user_id;
        this.instrument_type = instrument_type;
        this.instrument_id = instrument_id;
        this.order_type = order_type;
        this.side = side;
        this.quantity = quantity;
        this.limit_price = limit_price;
        this.status = status;
        this.filled_quantity = filled_quantity;
        this.average_fill_price = average_fill_price;
        this.exchange_fee = exchange_fee;
        this.created_at = created_at;
        this.updated_at = updated_at;
        this.expires_at = expires_at;
    }

    public String getOrder_id() { return order_id; }
    public String getPlatform_id() { return platform_id; }
    public String getPlatform_user_id() { return platform_user_id; }
    public String getInstrument_type() { return instrument_type; }
    public String getInstrument_id() { return instrument_id; }
    public String getOrder_type() { return order_type; }
    public String getSide() { return side; }
    public Integer getQuantity() { return quantity; }
    public Double getLimit_price() { return limit_price; }
    public String getStatus() { return status; }
    public Integer  getFilled_quantity() { return filled_quantity; }
    public Double getAverage_fill_price() { return average_fill_price; }
    public Double getExchange_fee() { return exchange_fee; }
    public String getCreated_at() { return LUtils.longToIsoDate(created_at); }
    public String getUpdated_at() { return LUtils.longToIsoDate(updated_at); }
    public String getExpires_at() { return LUtils.longToIsoDate(expires_at); }

    public static Order getDummy(String order_id) {
        return new Order(
                order_id,
                "platform-abc-123",
                "user-abc-123",
                "STOCK",
                "ARKA",
                "LIMIT",
                "BUY",
                50,
                128.0,
                "FILLED",
                50,
                12.34,
                1.23,
                1710511200L,
                1710511200L,
                1710511200L
        );
    }
}
